spring:
  application:
    name: jens-tasklist

camunda:
  client:
    rest-address: http://localhost:8088
    auth:
      method: basic
      username: demo
      password: demo

server:
  port: 8080